import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree, JetBrains_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google"
import { Manrope } from "next/font/google"
import { Plus_Jakarta_Sans } from "next/font/google"
import { Providers } from "@/app/provider";
import { AppSidebar } from "@/components/side-bar/app-sidebar"
import { SidebarTrigger } from "@/components/ui/sidebar"


const inter = Inter({
  subsets: ["latin"]});  

const manrope = Manrope({
  subsets: ["latin"]});  

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"]});  

  

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
})

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    
     <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <AppSidebar />

          <main className="flex-1">
            <SidebarTrigger />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
